SUBROUTINE FOILPRESSURE(N,NDIM,NCON,COSTH,SINTH,L,ALPHA,ALPHACOUNT,NALPHA,XBAR,YBAR,X,Y, &
VINF,BVEC,PI,ONEO2PI,PINF,DENSITY,P,U,V,LTOTAL,CL,NETSOURCE,BIGGAMMA,VT,M)

INTEGER :: N,SHARP,I,J,K,B,E,NDIM,ALPHACOUNT,NALPHA
INTEGER :: NCON(N,2),IPVT(NDIM)
REAL*8 :: VINF,CHORD,PI,ONEO2PI,ALPHA(NALPHA),DX,DY,DX1,DY1,DX2,DY2,RIJ,RIJPI,RKJ,RKJP1, &
BETAIJ,BETAKJ,SINTHIJ,COSTHIJ,SINTHKJ,COSTHKJ
REAL*8 :: COND,DENSITY,PINF,LTOTAL,CL(NALPHA),NETSOURCE,BIGGAMMA
REAL*8 :: X(NDIM),Y(NDIM),L(N),SINTH(N),COSTH(N),BVEC(NDIM),A(NDIM,NDIM)
REAL*8 :: XBAR(N),YBAR(N),VT(N),M(NDIM),P(N),U(N),V(N)

! REDEFINE VECTOR B AS M

M=BVEC

WRITE(*,*) 'M ='
WRITE(*,*) M

! COMPUTE PARAMETERS OF FLOW

DO I=1,N

	! COMPUTE TANGENTIAL VELOCITY
	
	VT(I)=VINF*(COSTH(I)*DCOS(ALPHA(ALPHACOUNT))+SINTH(I)*DSIN(ALPHA(ALPHACOUNT)))
	
	DO J=1,N
	
		B=NCON(J,1)
		E=NCON(J,2)
		
		DX1=XBAR(I)-X(B)
		DY1=YBAR(I)-Y(B)
		DX2=XBAR(I)-X(E)
		DY2=YBAR(I)-Y(E)
		
		RIJ=DSQRT(DX1*DX1+DY1*DY1)
		RIJP1=DSQRT(DX2*DX2+DY2*DY2)
		
		BETAIJ=DATAN2(DY2*DX1-DX2*DY1,DY1*DY2+DX1*DX2)
		
		IF (I==J) THEN
			BETAIJ=PI
		END IF
		
		SINTHIJ=SINTH(I)*COSTH(J)-COSTH(I)*SINTH(J)
		COSTHIJ=COSTH(I)*COSTH(J)+SINTH(I)*SINTH(J)
		
		! ACCUMULATE TANGENTIAL VELOCITY
		
		VT(I)=VT(I)+M(J)*ONEO2PI*(BETAIJ*SINTHIJ-COSTHIJ*DLOG(RIJP1/RIJ)) &
		+M(N+1)*ONEO2PI*(SINTHIJ*DLOG(RIJP1/RIJ)+BETAIJ*COSTHIJ)
		
	END DO
END DO

DO I=1,N

	! COMPUTE PRESSURE AND COMPONENTS OF VELOCITY

	P(I)=PINF+0.5D0*DENSITY*(VINF*VINF-VT(I)*VT(I))
	U(I)=VT(I)*COSTH(I)
	V(I)=VT(I)*SINTH(I)
	
END DO

! FIND PERIMETER OF AIRFOIL

LTOTAL=0.0D0
DO I=1,N
	LTOTAL=LTOTAL+L(I)
END DO

! COMPUTE LIFT COEFFICIENT

CL(ALPHACOUNT)=2.0D0*M(N+1)/VINF*LTOTAL

! COMPUTE NET SOURCE

NETSOURCE=0.0D0
DO I=1,N
	NETSOURCE=NETSOURCE+M(I)*L(I)
END DO

! COMPUTE NET VORTEX

BIGGAMMA=M(N+1)*LTOTAL

! OUTPUT RESULTS

WRITE(*,*) 'VT ='
WRITE(*,*) VT

WRITE(*,*) 'P ='
WRITE(*,*) P

WRITE(*,*) 'U ='
WRITE(*,*) U

WRITE(*,*) 'V ='
WRITE(*,*) V

WRITE(*,*) 'NET SOURCE ='
WRITE(*,*) NETSOURCE

WRITE(*,*) 'BIG GAMMA ='
WRITE(*,*) BIGGAMMA

RETURN
END