PROGRAM FOILDRIVER

INTEGER :: N,SHARP,I,J,K,B,E,NDIM,ALPHACOUNT,NALPHA,INPUT
INTEGER, ALLOCATABLE :: NCON(:,:),IPVT(:)
REAL*8 :: VINF,CHORD,PI,ONEO2PI,DX,DY,DX1,DY1,DX2,DY2,RIJ,RIJPI,RKJ,RKJP1,BETAIJ,BETAKJ,SINTHIJ,COSTHIJ,SINTHKJ,COSTHKJ
REAL*8 :: COND,DENSITY,PINF,LTOTAL,NETSOURCE,BIGGAMMA
REAL*8, ALLOCATABLE :: X(:),Y(:),L(:),SINTH(:),COSTH(:),BVEC(:),A(:,:), &
XBAR(:),YBAR(:),WORK(:),VT(:),M(:),P(:),U(:),V(:),ALPHA(:),CL(:)

! DEFINE CONSTANTS

VINF=1.0D0
CHORD=1.0D0
DENSITY=1.0D0
PINF=0.0D0
PI=4.0D0*DATAN(1.0D0)
ONEO2PI=0.5D0/PI
TWOPI=2.0D0*PI
NALPHA=1
ALLOCATE(ALPHA(NALPHA))

! DETERMINE SOURCE OF INPUT DATA

WRITE(*,*) 'ENTER 1 FOR DATA FILE, 0 FOR NACA'
READ(*,*) INPUT

IF (INPUT==1) THEN

	! READ DATA FROM FILE

	OPEN(UNIT=1,FILE='foiltest.txt')
	
	READ(1,*) N
	
	ALLOCATE(X(N),Y(N))
	
	DO I=1,N
		READ(1,*) X(I),Y(I)
	END DO
	
	DO I=1,NALPHA
		READ(1,*) ALPHA(I)
	END DO
	
ELSE

	! READ NUMBER OF PANELS

	WRITE(*,*) 'ENTER NUMBER OF PANELS (EVEN)'
	READ(*,*) N
	
	ALLOCATE(X(N),Y(N))
	
	! GENERATE AIRFOIL
	
	CALL FOILNACA(X,Y,N)
	
	! READ ANGLES OF ATTACK
	
	DO I=1,NALPHA
		WRITE(*,*) 'ENTER ALPHA'
		READ(*,*) ALPHA(I)
	END DO
	
END IF

! DETERMINE IF BODY IS BLUNT OR SHARP

WRITE(*,*) 'ENTER 1 FOR AIRFOIL, 0 FOR BLUNT BODY'
READ(*,*) SHARP

! ALLOCATE VARIABLES

NDIM=N+SHARP

ALLOCATE(L(N),SINTH(N),COSTH(N),XBAR(N),YBAR(N),NCON(N,2),A(NDIM,NDIM),BVEC(NDIM))
ALLOCATE(M(NDIM),WORK(NDIM),IPVT(NDIM),VT(N),P(N),U(N),V(N),CL(NALPHA))

! DO CALCULATIONS

DO ALPHACOUNT=1,NALPHA

CALL FOILPROPS(VINF,PI,ONEO2PI,N,X,Y,ALPHA,ALPHACOUNT,NALPHA,L,SINTH,COSTH,BVEC,A,SHARP,NCON,XBAR,YBAR)

CALL DECOMP(NDIM,NDIM,COND,IPVT,WORK,A)
CALL SOLVE(NDIM,NDIM,BVEC,IPVT,A)

CALL FOILPRESSURE(N,NDIM,NCON,COSTH,SINTH,L,ALPHA,ALPHACOUNT,NALPHA,XBAR,YBAR,X,Y,VINF,BVEC,PI, &
ONEO2PI,PINF,DENSITY,P,U,V,LTOTAL,CL,NETSOURCE,BIGGAMMA,VT,M)

END DO

CALL FOILPOSTPROC(ALPHA,NALPHA,CL,TWOPI)

END PROGRAM