SUBROUTINE FOILPOSTPROC(ALPHA,NALPHA,CL,TWOPI)

REAL*8 :: ALPHA(NALPHA),CL(NALPHA),SLOPE

! COMPUTE LIFT SLOPE

SLOPE=(CL(2)-CL(1))/(ALPHA(2)-ALPHA(1))

! OUTPUT RESULTS

WRITE(*,*) 'CL ='
WRITE(*,*) CL

WRITE(*,*) 'LIFT SLOPE =',SLOPE

! CHECK LIFT SLOPE

WRITE(*,*) '2 PI =',TWOPI

RETURN
END