SUBROUTINE CURVEZMAT(X,NBASIS,NPOINTS,Z)

INTEGER :: NPOINTS,NBASIS,I,J
REAL*8 :: X(NPOINTS),A(NBASIS),Z(NBASIS,NPOINTS),F(NBASIS)

! USE BASIS FUNCTIONS TO CONSTRUCT Z MATRIX

DO I=1,NPOINTS
	CALL CURVEBASIS(X(I),F,NBASIS)
	DO J=1,NBASIS
		Z(J,I)=F(J)
	END DO
END DO

RETURN
END