SUBROUTINE RK4(Y,H,N,X)

REAL*8 :: Y(N),X,H,K1(N),K2(N),K3(N),K4(N),XNEW,YNEW(N)
INTEGER :: N,I

! CALCULATE ALL STATE VARIABLES

CALL SLOPE(Y,X,K1,N)

! INCREASE X BY HALF OF A STEP SIZE

XNEW=X+H*0.5D0

! FIND NEW Y USING NEW SLOPES

DO I=1,N
	YNEW(I)=Y(I)+0.5D0*K1(I)*H
END DO

! CALCULATE NEW STATE VARIABLES

CALL SLOPE(YNEW,XNEW,K2,N)

! FIND NEW Y USING NEW SLOPES

DO I=1,N
	YNEW(I)=Y(I)+0.5D0*K2(I)*H
END DO

! CALCULATE NEW STATE VARIABLES

CALL SLOPE(YNEW,XNEW,K3,N)

! X VALUE OF THE NEXT STEP

XNEW=X+H

! FIND NEW Y USING NEW SLOPES

DO I=1,N
	YNEW(I)=Y(I)+K3(I)*H
END DO

! CALCULATE NEW STATE VARIABLES

CALL SLOPE(YNEW,XNEW,K4,N)

! CALCULATE FINAL Y USING ALL SLOPES FROM THE RK4 METHOD

DO I=1,N
	Y(I)=Y(I)+H/6.0D0*(K1(I)+2*(K2(I)+K3(I))+K4(I))
END DO

! SET X TO THE X VALUE OF THE NEXT STEP

X=XNEW

RETURN
END