SUBROUTINE trusspost(NPINS,GIVEN,DISP,VALUE,FORCE,F)

INTEGER :: I,J,K,GIVEN(2*NPINS)
REAL*8 :: DISP(2*NPINS),VALUE(2*NPINS),FORCE(2*NPINS),F(2*NPINS)
!
! SORT VALUES INTO FORCES AND DISPLACEMENTS
!
J=1
K=1
DO I=1,2*NPINS
	IF (GIVEN(I) == 0) THEN
		DISP(I)=VALUE(I)
		F(I)=FORCE(I)
	ELSE
		DISP(I)=FORCE(I)
		F(I)=VALUE(I)
	END IF
	IF (J < 2) THEN
		WRITE(*,*) 'PIN',K
		WRITE(*,*) 'U x =',DISP(I),'F x =',F(I)
		J=J+1
		K=K+1
	ELSE
		WRITE(*,*) 'U y =',DISP(I),'F y =',F(I)
		J=1
	END IF
END DO

RETURN
END