SUBROUTINE trussarrange(NPINS,STIFF,FORCE,GIVEN,VALUE)

INTEGER :: I,J,GIVEN(2*NPINS)
REAL*8 :: STIFF(2*NPINS,2*NPINS),FORCE(2*NPINS),VALUE(2*NPINS)
!
! REARRANGE MATRICES INTO KNOWNS AND UNKNOWNS
!
DO I=1,2*NPINS
	READ(1,*) GIVEN(I)
	READ(1,*) VALUE(I)
	IF (GIVEN(I)==0) THEN
		DO J=1,2*NPINS
			FORCE(J)=FORCE(J)-STIFF(J,I)*VALUE(I)
		END DO
		DO J=1,2*NPINS
			STIFF(J,I)=0.0
		END DO
		STIFF(I,I)=-1.0
	ELSE
		FORCE(I)=FORCE(I)+VALUE(I)
	END IF
END DO

RETURN
END