SUBROUTINE trussdef(NPINS,NMEM,NCON,X,Y,AREA,YOUNG)

INTEGER :: NPINS,NMEM,I,NCON(NMEM,2)
REAL*8 :: X(NPINS),Y(NPINS),AREA(NMEM),YOUNG(NMEM)
!
! READ CONNECTIVITY MATRIX
!
DO I=1,NMEM
	READ(1,*) NCON(I,1)
	READ(1,*) NCON(I,2)
END DO
!
! READ PIN POSITIONS
!
DO I=1,NPINS
	READ(1,*) X(I)
	READ(1,*) Y(I)
END DO
!
! READ MEMBER PROPERTIES
!
DO I=1,NMEM
	READ(1,*) AREA(I)
	READ(1,*) YOUNG(I)
END DO

RETURN
END