PROGRAM trussdrive

INTEGER :: NPINS,NMEM,NDIM,N
INTEGER, ALLOCATABLE :: NCON(:,:),IPVT(:),GIVEN(:)
REAL*8, ALLOCATABLE :: X(:),Y(:),AREA(:),YOUNG(:),STIFF(:,:),FORCE(:),WORK(:),VALUE(:),DISP(:),F(:)
REAL*8 :: COND

OPEN(UNIT=1,FILE='trusstest.txt')

READ(1,*) NPINS
READ(1,*) NMEM

ALLOCATE(NCON(NMEM,2),X(NPINS),Y(NPINS),AREA(NMEM),YOUNG(NMEM),STIFF(2*NPINS,2*NPINS))
ALLOCATE(FORCE(2*NPINS),WORK(2*NPINS),IPVT(2*NPINS),GIVEN(2*NPINS),VALUE(2*NPINS),DISP(2*NPINS),F(2*NPINS))

CALL trussdef(NPINS,NMEM,NCON,X,Y,AREA,YOUNG)

CALL trussprops(NPINS,NMEM,NCON,X,Y,AREA,YOUNG,STIFF)

CALL trussarrange(NPINS,STIFF,FORCE,GIVEN,VALUE)

NDIM=2*NPINS
N=NDIM

CALL DECOMP(NDIM,N,COND,IPVT,WORK,STIFF)
CALL SOLVE(NDIM,N,FORCE,IPVT,STIFF)

CALL trusspost(NPINS,GIVEN,DISP,VALUE,FORCE,F)

END PROGRAM